#!/usr/bin/env python3
"""Build state/schedule.json from content/posts.py.

Day 1 is Monday 28 September 2026. Every post gets a Dubai-time slot picked for
when a UAE audience is actually on Instagram and Facebook:

  Mon-Thu  20:00  after work and the commute - the evening scroll peak
  Fri      19:00  start of the weekend, people are out but on their phones
  Sat      12:00  weekend late morning, before plans
  Sun      20:00  back-to-work evening, owners planning the week

Stories (content/stories.py), every day:
  am    09:00 GST, the Highlight frame
  push  feed slot + 30 min, only once that day's post is live on Instagram.
        Reel days are posted by hand after the Reel goes up (auto: false).
  ask   days 7 and 19, poll/quiz background posted by hand (auto: false).

Captions are resolved here for each platform ({CTA} and {LINK}) so publish.py
and schedule_facebook.py only ever send what is written in the schedule.

Usage: python3 scripts/build_schedule.py
"""

import json
import os
import sys
from datetime import date, datetime, time, timedelta, timezone

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "content"))
from posts import FEED_DAYS, POSTS, REELS, link  # noqa: E402
from stories import AM, ASK  # noqa: E402

DAY1 = date(2026, 9, 28)
GST = timezone(timedelta(hours=4))
SLOTS = {0: time(20, 0), 1: time(20, 0), 2: time(20, 0), 3: time(20, 0),
         4: time(19, 0), 5: time(12, 0), 6: time(20, 0)}

MEDIA_BASE = "https://nexvate.ae/social/launch30/"
IG_USER_ID = "17841441428644524"   # @nexvate.ae
FB_PAGE_ID = "1201189833088043"    # Nexvate


def caption(post, platform):
    cta = post["cta_ig"] if platform == "ig" else post["cta_fb"]
    text = post["caption"].replace("{CTA}", cta).replace("{LINK}", link(post["path"], post["day"]))
    text += "\n\n" + " ".join("#" + t for t in post["hashtags"])
    return text


def main():
    posts = []
    for p in POSTS:
        d = DAY1 + timedelta(days=p["day"] - 1)
        local = datetime.combine(d, SLOTS[d.weekday()], GST)
        n = len(p["slides"])
        posts.append({
            "id": f"nx-d{p['day']:02d}",
            "day": p["day"],
            "pillar": p["pillar"],
            "title": p["slides"][0]["title"].replace("<br>", " "),
            "media_type": "CAROUSEL" if n > 1 else "IMAGE",
            "media": [f"{MEDIA_BASE}d{p['day']:02d}-{i + 1}.jpg" for i in range(n)],
            "caption_ig": caption(p, "ig"),
            "caption_fb": caption(p, "fb"),
            "ig_user_id": IG_USER_ID,
            "fb_page_id": FB_PAGE_ID,
            "publish_at_gst": local.strftime("%a %d %b %Y %H:%M"),
            "publish_at_utc": local.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        })
    stories = []
    for day in range(1, 31):
        d = DAY1 + timedelta(days=day - 1)
        frames = [("am", datetime.combine(d, time(9, 0), GST), True, None, AM[day]["hl"])]
        if day in FEED_DAYS:
            push = datetime.combine(d, SLOTS[d.weekday()], GST) + timedelta(minutes=30)
            frames.append(("push", push, day not in REELS, None if day in REELS else f"nx-d{day:02d}", None))
        if day in ASK:
            frames.append(("ask", datetime.combine(d, SLOTS[d.weekday()], GST), False, None, None))
        for kind, local, auto, after, hl in frames:
            stories.append({
                "id": f"nx-s{day:02d}-{kind}",
                "day": day,
                "kind": kind,
                "highlight": hl,
                "auto": auto,
                "after": after,
                "media": f"{MEDIA_BASE}stories/s{day:02d}-{kind}.jpg",
                "ig_user_id": IG_USER_ID,
                "fb_page_id": FB_PAGE_ID,
                "publish_at_gst": local.strftime("%a %d %b %Y %H:%M"),
                "publish_at_utc": local.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            })
    os.makedirs(os.path.join(ROOT, "state"), exist_ok=True)
    with open(os.path.join(ROOT, "state", "schedule.json"), "w", encoding="utf-8") as f:
        json.dump({
            "generated_note": "Generated by scripts/build_schedule.py from content/posts.py. Do not hand-edit.",
            "timezone": "Asia/Dubai",
            "posts": posts,
            "stories": stories,
        }, f, indent=2, ensure_ascii=False)
        f.write("\n")
    for p in posts:
        print(f"{p['id']}  {p['publish_at_gst']} GST  {p['media_type']:<8} {len(p['media']):>2} img  "
              f"ig {len(p['caption_ig']):>4}  {p['title'][:48]}")


    auto = sum(s["auto"] for s in stories)
    print(f"\nstories: {len(stories)} ({auto} automatic, {len(stories) - auto} by hand)")


if __name__ == "__main__":
    main()
